name: Run Cypress Test from Repo B

on:
  repository_dispatch:
    types: [run-cypress-from-repo-b]
  schedule:
    # every 1 minute from 6am-7pm EDT, Monday-Sunday
    - cron: */1 * * * *
  workflow_dispatch:
    inputs:
      environment: 
        description: 'Environment on which you want to run the WebSocket tests'
        required: true
        default: dev
        type: choice
        options:
          - dev
          - qa
          - test

jobs:
  run-specific-cypress-test:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger echo
        run: echo "test"
      - name: Run WebSocket Test
        run: echo "$ENV"
        env:
          ENV: ${{ github.event.client_payload.environment || github.event.inputs.environment || 'dev123' }}
