name: Run Cypress Test from Repo B

on:
  repository_dispatch:
    types: [run-cypress-from-repo-b]

jobs:
  run-specific-cypress-test:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger echo
        run: echo "test"
      - name: Run WebSocket Test
        run: echo "$ENV"
        env:
          ENV: ${{ github.event.client_payload.environment }}
