name: Run Cypress Test from Repo B

on:
  repository_dispatch:
    types: [run-cypress-from-repo-b]

jobs:
  run-specific-cypress-test:
    if: github.event.action == 'run-cypress-from-repo-b'
    runs-on: ubuntu-latest

    steps:
      - name: Trigger echo
        run: echo "test"