name: Execute workflow

on:
  workflow_run:
    workflows: ["Run Cypress Test from Repoo B"]
    types:
      - completed

jobs:
  extract-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Print workflow A run-name
        run: |
          RUN_NAME="${{ github.event.workflow_run.name }}"
          echo "Run name: $RUN_NAME"
      
          LAST_WORD=$(echo "$RUN_NAME" | awk '{print $NF}' | tr -d "'\"")
      
          if [[ "$LAST_WORD" == "dev" || "$LAST_WORD" == "qa" || "$LAST_WORD" == "test" ]]; then
            echo "Run name: $LAST_WORD"
          else
            echo "env=unknown" >> $GITHUB_OUTPUT
          fi
