name: Execute workflow

on:
  workflow_run:
    workflows:
      - Run Cypress Test from Repoo B
      - Test workflow
    types:
      - completed

jobs:
  extract-environment:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Infer environment from run-name
        id: infer_env
        run: |
          RUN_NAME="${{ github.event.workflow_run.name }}"
          echo "Run name: $RUN_NAME"
      
          TEST_ENVIRONMENT=$(echo "$RUN_NAME" | awk '{print $NF}' | tr -d "'\"")
      
          if [[ "$TEST_ENVIRONMENT" == "dev" || "$TEST_ENVIRONMENT" == "qa" || "$TEST_ENVIRONMENT" == "test" ]]; then
            echo "env=$TEST_ENVIRONMENT" >> $GITHUB_OUTPUT
          else
            echo "env=unknown" >> $GITHUB_OUTPUT
          fi
          
      - name: Trigger cypress test
        run: |
          echo "The environment is: ${{ steps.infer_env.outputs.env }}"
